export const siteConfig = {
  name: 'NaturesMud',
  legalName: 'NaturesMud Nepal',
  alternateNames: ['NaturesMud Nepal', "Nature's Mud", 'Nature Mud', 'naturesmud', 'नेचर्स मड'],
  tagline: 'Pure Food · Real Nature · 0 Additives · 0 Preservatives',
  description:
    'NaturesMud Nepal delivers 100% pure naturally dehydrated fruits, freeze-dried & solar-dried superfood powders (Avocado, Banana, Strawberry, Moringa, Sweet Potato, Beetroot, Dates, Carrot), mountain nuts, seeds, cold-pressed virgin coconut oil, and Himalayan salts across Kathmandu, Pokhara, Chitwan, Butwal, Biratnagar & all of Nepal. 0 Additives, 0 Preservatives, 0 Added Sugar.',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://naturesmud.shop',
  secondaryUrl: 'https://naturesmud.com',
  primaryDomain: 'naturesmud.shop',
  mirrorDomain: 'naturesmud.com',
  phone: '+977-9713888002',
  secondaryPhone: '+977-9713888002',
  whatsappNumber: '9779713888002',
  whatsappMessage: 'Hello NaturesMud Nepal! I would like to order pure superfoods & naturally dehydrated fruits.',
  email: 'info@naturesmud.shop',
  secondaryEmail: 'info@naturesmud.shop',
  supportEmail: 'info@naturesmud.shop',
  privacyEmail: 'info@naturesmud.shop',
  address: 'Baneshwor, Kathmandu 44600, Nepal',
  businessHours: 'Sunday – Friday: 9:00 AM – 6:00 PM NPT',
  locationDetails: {
    headquarters: 'Baneshwor, Kathmandu 44600, Nepal',
    outlets: [
      'Kids Kottage — Arya Complex, Kathmandu (Partner Outlet Ph: 9802323451)',
      'Kids Kottage — Kupondol, Lalitpur & Kapan, Kathmandu',
      'Zero to Ten — Chabahil, Kathmandu',
      'Kids Kottage — Surkhet',
      'Kids Kottage — Pokhara',
      'Baby Love — Hetauda',
    ],
  },
  social: {
    facebook: 'https://www.facebook.com/profile.php?id=61589084257990',
    instagram: 'https://www.instagram.com/naturesmud_official/',
    tiktok: 'https://www.tiktok.com/@naturesmud',
    youtube: 'https://youtube.com/@naturesmud',
  },
  freeShippingThreshold: 3000,
  shipping: {
    freeThreshold: 3000,
    insideValleyFee: 100,
    majorCitiesFee: 150,
    outsideValleyFee: 200,
    insideValleyEta: '24–48 hours (1–2 business days)',
    majorCitiesEta: '2–4 business days',
    remoteRegionsEta: '3–7 business days',
  },
  metrics: {
    familiesServed: '25,000+',
    verifiedOrders: '3,840+',
    farmerFamiliesTotal: '280+',
    farmerBreakdown: {
      terai: '110+ Smallholder Farming Families (Chitwan, Jhapa, Nawalpur, Sarlahi)',
      hilly: '95+ Organic Hill Collectives (Kavre, Sindhupalchok, Palpa, Ilam)',
      himalaya: '75+ Indigenous Alpine Harvesters (Mustang, Jumla, Manang, Dolpa)',
    },
    ecologicalBelts: 3,
  },
  currency: 'Rs.',
};

export const navLinks = [
  { label: 'Home', href: '/' },
  { label: 'Shop', href: '/products' },
  { label: 'Catalog', href: '/catalog' },
  { label: 'Festival Offers', href: '/offers' },
  { label: 'Our Story', href: '/about' },
  { label: 'Recipes', href: '/recipes' },
  { label: 'Blog', href: '/blog' },
  { label: 'FAQ', href: '/faq' },
  { label: 'Contact', href: '/contact' },
];

export const footerLinks = {
  company: [
    { label: 'Catalog', href: '/catalog' },
    { label: 'About Us & Sourcing', href: '/about' },
    { label: 'Our Himalayan Story', href: '/about#sourcing-journey' },
    { label: 'Festival Offers & Combos', href: '/offers' },
    { label: 'Health & Nutrition Blog', href: '/blog' },
    { label: 'Wellness Recipes', href: '/recipes' },
    { label: 'Contact & Showrooms', href: '/contact' },
  ],
  products: [
    { label: 'Naturally Dehydrated Fruits', href: '/products?category=dried-fruits' },
    { label: 'Organic Superfood Powders', href: '/products?category=powders' },
    { label: 'Mountain Nuts & Cashews', href: '/products?category=nuts' },
    { label: 'Organic Seeds (Chia & Pumpkin)', href: '/products?category=seeds' },
    { label: 'Cold-Pressed Virgin Oils', href: '/products?category=oils' },
    { label: 'Himalayan Rock Salts', href: '/products?category=salts-spices' },
  ],
  support: [
    { label: 'FAQ & Help', href: '/faq' },
    { label: 'Track My Order', href: '/track-order' },
    { label: 'Shipping Across Nepal', href: '/shipping-policy' },
    { label: 'Return & Refund Policy', href: '/return-policy' },
    { label: 'Privacy Policy', href: '/privacy-policy' },
    { label: 'Terms & Conditions', href: '/terms' },
  ],
  business: [
    { label: 'Catalog', href: '/Nature_Mud_Product_Catalog.pdf' },
    { label: 'Wholesale Inquiries', href: '/wholesale' },
    { label: 'Become a Retail Distributor', href: '/become-distributor' },
  ],
};