<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $categories = Category::pluck('id', 'slug')->toArray();

        $products = [
            [
                'name' => 'Himalayan Walnuts',
                'slug' => 'himalayan-walnuts',
                'category' => 'nuts',
                'price' => 390,
                'compare_at_price' => 480,
                'short_description' => 'Premium walnuts sourced from high-altitude Himalayan orchards.',
                'stock_quantity' => 100,
                'is_featured' => true,
                'is_best_seller' => true,
                'weight' => 100,
            ],
            [
                'name' => 'Raw Himalayan Almonds',
                'slug' => 'raw-himalayan-almonds',
                'category' => 'nuts',
                'price' => 360,
                'short_description' => 'Crunchy, naturally grown almonds from the hills of Nepal.',
                'stock_quantity' => 100,
                'is_featured' => true,
                'weight' => 100,
            ],
            [
                'name' => 'Premium Roasted Almonds',
                'slug' => 'premium-roasted-almonds',
                'category' => 'nuts',
                'price' => 360,
                'compare_at_price' => 440,
                'short_description' => 'Slow-roasted almonds packed with Vitamin E and healthy fats.',
                'stock_quantity' => 120,
                'is_best_seller' => true,
                'is_featured' => true,
                'weight' => 100,
            ],
            [
                'name' => 'Dried Blueberries',
                'slug' => 'dried-blueberries',
                'category' => 'dried-fruits',
                'price' => 650,
                'compare_at_price' => 780,
                'short_description' => 'Little berries, big goodness. Naturally sweet, no preservatives.',
                'stock_quantity' => 70,
                'is_best_seller' => true,
                'weight' => 100,
            ],
            [
                'name' => 'Beetroot Powder',
                'slug' => 'beetroot-powder',
                'category' => 'powders',
                'price' => 380,
                'short_description' => 'Enhances blood flow, athletic stamina & immunity naturally.',
                'stock_quantity' => 90,
                'is_featured' => true,
                'weight' => 100,
            ],
            [
                'name' => 'Dates Powder',
                'slug' => 'dates-powder',
                'category' => 'powders',
                'price' => 390,
                'compare_at_price' => 480,
                'short_description' => 'Sustained energy fuel, no added sugar. Pre-workout power!',
                'stock_quantity' => 110,
                'is_best_seller' => true,
                'is_new' => true,
                'weight' => 100,
            ],
            [
                'name' => 'Dehydrated Apple',
                'slug' => 'dehydrated-apple',
                'category' => 'dried-fruits',
                'price' => 320,
                'short_description' => 'Premium dehydrated apple — 100% natural, no preservatives.',
                'stock_quantity' => 100,
                'weight' => 100,
            ],
            [
                'name' => 'Premium Coconut Oil',
                'slug' => 'premium-coconut-oil',
                'category' => 'superfoods',
                'price' => 290,
                'compare_at_price' => 350,
                'short_description' => 'Extra virgin coconut oil for cooking, skin & hair.',
                'stock_quantity' => 60,
                'is_featured' => true,
                'weight' => 100,
            ],
            [
                'name' => 'Dried Cranberries',
                'slug' => 'dried-cranberries',
                'category' => 'dried-fruits',
                'price' => 380,
                'compare_at_price' => 460,
                'short_description' => 'Tart, antioxidant-rich cranberries with no artificial preservatives.',
                'stock_quantity' => 80,
                'is_best_seller' => true,
                'is_featured' => true,
                'weight' => 100,
            ],
            [
                'name' => 'Mustard Seeds',
                'slug' => 'mustard-seeds',
                'category' => 'seeds',
                'price' => 200,
                'short_description' => 'Dark, aromatic mustard seeds freshly harvested from Nepali farms.',
                'stock_quantity' => 150,
                'is_best_seller' => true,
                'weight' => 100,
            ],
            [
                'name' => 'Chia Seeds',
                'slug' => 'chia-seeds',
                'category' => 'seeds',
                'price' => 250,
                'short_description' => 'Omega-3 rich chia seeds for a superfood boost.',
                'stock_quantity' => 80,
                'is_best_seller' => true,
                'is_new' => true,
                'weight' => 100,
            ],
            [
                'name' => 'Yarsagumba Powder',
                'slug' => 'yarsagumba-powder',
                'category' => 'superfoods',
                'price' => 4500,
                'compare_at_price' => 5000,
                'short_description' => 'Rare Himalayan caterpillar fungus, finely ground.',
                'stock_quantity' => 20,
                'is_featured' => true,
                'weight' => 50,
            ],
            [
                'name' => 'Raw Honey',
                'slug' => 'raw-honey',
                'category' => 'superfoods',
                'price' => 380,
                'short_description' => 'Pure, unfiltered honey collected from Himalayan wildflowers.',
                'stock_quantity' => 60,
                'is_best_seller' => true,
                'is_featured' => true,
                'weight' => 100,
            ],
            [
                'name' => 'Turmeric Powder',
                'slug' => 'turmeric-powder',
                'category' => 'powders',
                'price' => 180,
                'short_description' => 'Bright golden turmeric powder from organic Nepali farms.',
                'stock_quantity' => 200,
                'is_best_seller' => true,
                'weight' => 100,
            ],
            [
                'name' => 'Ginger Powder',
                'slug' => 'ginger-powder',
                'category' => 'powders',
                'price' => 250,
                'short_description' => 'Aromatic sun-dried ginger powder.',
                'stock_quantity' => 120,
                'weight' => 100,
            ],
            [
                'name' => 'Dried Apricots',
                'slug' => 'dried-apricots',
                'category' => 'dried-fruits',
                'price' => 380,
                'short_description' => 'Sun-dried Hunza apricots — sweet and naturally preserved.',
                'stock_quantity' => 90,
                'is_featured' => true,
                'weight' => 100,
            ],
            [
                'name' => 'Dried Apples',
                'slug' => 'dried-apples',
                'category' => 'dried-fruits',
                'price' => 320,
                'short_description' => 'Crispy dried apple rings from the apple orchards of Jumla.',
                'stock_quantity' => 110,
                'weight' => 100,
            ],
            [
                'name' => 'Flaxseed Crackers',
                'slug' => 'flaxseed-crackers',
                'category' => 'healthy-snacks',
                'price' => 220,
                'short_description' => 'Crunchy, gluten-free crackers packed with flaxseeds.',
                'stock_quantity' => 140,
                'is_best_seller' => true,
                'is_new' => true,
                'weight' => 100,
            ],
            [
                'name' => 'Himalayan Trail Mix',
                'slug' => 'himalayan-trail-mix',
                'category' => 'healthy-snacks',
                'price' => 380,
                'compare_at_price' => 460,
                'short_description' => 'A perfect blend of nuts, seeds, and dried fruits.',
                'stock_quantity' => 130,
                'is_featured' => true,
                'is_best_seller' => true,
                'weight' => 100,
            ],
            [
                'name' => 'Immunity Shield Superfood Mix',
                'slug' => 'immunity-shield-superfood-mix',
                'category' => 'superfoods',
                'price' => 480,
                'compare_at_price' => 580,
                'short_description' => 'Premium superfood blend to boost immunity and daily vitality.',
                'stock_quantity' => 50,
                'is_featured' => true,
                'is_best_seller' => true,
                'is_new' => true,
                'weight' => 100,
            ],
            [
                'name' => 'Organic Pumpkin Seeds',
                'slug' => 'organic-pumpkin-seeds',
                'category' => 'seeds',
                'price' => 280,
                'compare_at_price' => 350,
                'short_description' => 'Zinc-rich organic seeds for immunity and restful sleep.',
                'stock_quantity' => 65,
                'weight' => 100,
            ],
            [
                'name' => 'Dehydrated Papaya',
                'slug' => 'dehydrated-papaya',
                'category' => 'dried-fruits',
                'price' => 250,
                'short_description' => 'Tropical papaya pieces with natural papain for gut health.',
                'stock_quantity' => 55,
                'is_new' => true,
                'weight' => 100,
            ],
            [
                'name' => 'Himalayan Pink Salt',
                'slug' => 'himalayan-pink-salt',
                'category' => 'spices',
                'price' => 150,
                'compare_at_price' => 200,
                'short_description' => 'Pure Himalayan salt with 84+ trace minerals, unrefined and natural.',
                'stock_quantity' => 150,
                'weight' => 100,
            ],
        ];

        foreach ($products as $product) {
            $categoryId = $categories[$product['category']] ?? null;

            Product::updateOrCreate(
                ['slug' => $product['slug']],
                [
                    'category_id' => $categoryId,
                    'name' => $product['name'],
                    'sku' => 'NM-' . strtoupper(Str::slug($product['name'], '_')),
                    'description' => $product['short_description'] . ' 100% natural, no additives. Sourced responsibly from farmers across Nepal.',
                    'short_description' => $product['short_description'],
                    'price' => $product['price'],
                    'compare_at_price' => $product['compare_at_price'] ?? null,
                    'cost_price' => round($product['price'] * 0.6, 2),
                    'stock_quantity' => $product['stock_quantity'],
                    'low_stock_threshold' => 10,
                    'is_active' => true,
                    'is_featured' => $product['is_featured'] ?? false,
                    'is_best_seller' => $product['is_best_seller'] ?? false,
                    'is_new' => $product['is_new'] ?? false,
                    'weight' => $product['weight'],
                    'unit' => 'g',
                    'ingredients' => [$product['name']],
                    'benefits' => ['100% Natural', 'Rich in nutrients', 'No artificial colors', 'No added sugar'],
                    'nutrition_facts' => ['energy' => '250 kcal', 'protein' => '5g', 'fat' => '15g', 'carbs' => '20g'],
                    'usage_instructions' => 'Store in a cool, dry place. Consume within 6 months of opening.',
                    'storage_instructions' => 'Keep in an airtight container away from direct sunlight.',
                    'meta_title' => $product['name'] . ' | Nature\'s Mud',
                    'meta_description' => $product['short_description'],
                    'rating_avg' => rand(40, 50) / 10,
                    'rating_count' => rand(10, 200),
                    'sold_count' => rand(50, 1000),
                ]
            );
        }
    }
}