import Link from 'next/link';
import { notFound } from 'next/navigation';
import { masterBlogCatalog, getBlogPostBySlug, isAutoGeneratedBlogStub } from '@/lib/data/blogs-database';
import { api } from '@/lib/api';
import BlogPostClient from '@/components/BlogPostClient';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

export async function generateStaticParams() {
  return masterBlogCatalog.map((post) => ({
    slug: post.slug,
  }));
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) {
  const { slug: rawSlug } = await params;
  const slug = decodeURIComponent(rawSlug || '');
  let post: any = null;
  let fromApi = false;

  try {
    const res = await api.get(`/blogs/${slug}`);
    if (res.data) {
      fromApi = true;
      post = {
        id: String(res.data.id),
        slug: res.data.slug,
        title: res.data.title,
        excerpt: res.data.excerpt || '',
        content: (() => {
          let c = res.data.content || '';
          if (Array.isArray(c)) return c;
          if (typeof c === 'string') {
            try { 
              const parsed = JSON.parse(c); 
              if (Array.isArray(parsed)) return parsed;
            } catch(e) {}
            return c.split(/\n\s*\n/).filter(Boolean);
          }
          return [c];
        })(),
        image: res.data.featured_image || res.data.image || '/products/sweet-potato-powder-100g.jpg',
        category: res.data.category || 'Superfoods',
        author: res.data.author || "NaturesMud Editorial Team",
        date: res.data.published_at ? new Date(res.data.published_at).toLocaleDateString('en-US') : 'Recent',
        readTime: 10,
        tags: typeof res.data.tags === 'string' ? JSON.parse(res.data.tags) : res.data.tags || [],
      };
    }
  } catch (err: any) {
    post = getBlogPostBySlug(slug);
  }

  if (!post) {
    post = getBlogPostBySlug(slug);
  }

  if (!post) return {};

  const baseUrl = 'https://naturesmud.shop';
  const canonicalUrl = `${baseUrl}/blog/${post.slug}`;
  const imgUrl = post.image?.startsWith('http') ? post.image : `${baseUrl}${post.image || '/products/sweet-potato-powder-100g.jpg'}`;
  const isStub = !fromApi && isAutoGeneratedBlogStub(post.slug);

  return {
    title: post.title,
    description: post.metaDescription || post.excerpt,
    keywords: Array.isArray(post.tags)
      ? post.tags.join(', ')
      : 'pure food nepal, baby nutrition, himalayan superfoods, naturesmud nepal',
    robots: {
      index: !isStub,
      follow: true,
    },
    alternates: {
      canonical: canonicalUrl,
    },
    openGraph: {
      title: `${post.title} | NaturesMud Nepal`,
      description: post.metaDescription || post.excerpt,
      url: canonicalUrl,
      siteName: 'NaturesMud Nepal',
      images: [
        {
          url: imgUrl,
          width: 1200,
          height: 630,
          alt: post.title,
        },
      ],
      type: 'article',
    },
    twitter: {
      card: 'summary_large_image',
      title: `${post.title} | NaturesMud Nepal`,
      description: post.metaDescription || post.excerpt,
      images: [imgUrl],
    },
  };
}

export default async function BlogPostPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug: rawSlug } = await params;
  const slug = decodeURIComponent(rawSlug || '');
  let post: any = null;

  try {
    const res = await api.get(`/blogs/${slug}`);
    const localPost = getBlogPostBySlug(slug);
    if (res.data) {
      post = {
        id: String(res.data.id),
        slug: res.data.slug,
        title: res.data.title,
        excerpt: res.data.excerpt || '',
        content: (() => {
          let c = res.data.content || '';
          if (Array.isArray(c)) return c;
          if (typeof c === 'string') {
            try { 
              const parsed = JSON.parse(c); 
              if (Array.isArray(parsed)) return parsed;
            } catch(e) {}
            return c.split(/\n\s*\n/).filter(Boolean);
          }
          return [c];
        })(),
        image: res.data.featured_image || res.data.image || '/products/sweet-potato-powder-100g.jpg',
        category: res.data.category || 'Superfoods',
        author: res.data.author || 'NaturesMud Editorial Team',
        date: res.data.published_at
          ? new Date(res.data.published_at).toLocaleDateString('en-US', {
              month: 'short',
              day: 'numeric',
              year: 'numeric',
            })
          : 'Recent',
        readTime: res.data.read_time || res.data.readTime || 10,
        tags: typeof res.data.tags === 'string' ? JSON.parse(res.data.tags) : res.data.tags || [],
        keyTakeaways: res.data.keyTakeaways || res.data.key_takeaways || localPost?.keyTakeaways || [],
        wallpapers: res.data.wallpapers || localPost?.wallpapers || [],
        featuredProductName: res.data.featuredProductName || res.data.featured_product_name || localPost?.featuredProductName,
        featuredProductPrice: res.data.featuredProductPrice || res.data.featured_product_price || localPost?.featuredProductPrice,
        featuredProductSlug: res.data.featuredProductSlug || res.data.featured_product_slug || localPost?.featuredProductSlug,
        featuredProductImage: res.data.featuredProductImage || res.data.featured_product_image || localPost?.featuredProductImage,
        faqs: res.data.faqs || localPost?.faqs || [],
      };
    }
  } catch (err: any) {
    post = getBlogPostBySlug(slug);
  }

  if (!post) {
    post = getBlogPostBySlug(slug);
  }

  if (!post) notFound();

  const related = masterBlogCatalog
    .filter((p) => p.id !== post?.id && (p.category === post?.category || true))
    .slice(0, 3);

  const baseUrl = 'https://naturesmud.shop';
  const canonicalUrl = `${baseUrl}/blog/${post.slug}`;
  const imgUrl = post.image?.startsWith('http') ? post.image : `${baseUrl}${post.image || '/products/sweet-potato-powder-100g.jpg'}`;

  // Auto-generate accurate, non-fabricated FAQs for schema if none provided
  const activeFaqs = (post.faqs && post.faqs.length > 0) ? post.faqs : [
    {
      question: `What makes NaturesMud superfoods & powders different in Nepal?`,
      answer: `NaturesMud products are crafted from 100% pure whole-food ingredients with 0 artificial additives, 0 preservatives, and 0 added refined sugar, packed fresh in airtight containers.`
    },
    {
      question: `How should dehydrated fruits and superfood powders be stored in Nepal?`,
      answer: `Store all superfood powders, nuts, seeds, and dehydrated fruits in their tightly sealed jar or pouch in a cool, dry cupboard away from moisture and direct sunlight, always using a dry spoon.`
    },
    {
      question: `Do you deliver across Kathmandu Valley and outside valley in Nepal?`,
      answer: `Yes, NaturesMud delivers within 24–48 hours across Kathmandu, Lalitpur, and Bhaktapur, and ships nationwide to Pokhara, Chitwan, Butwal, Biratnagar, Dharan, Hetauda, Nepalgunj, Surkhet, and all 77 districts.`
    }
  ];

  const blogGraphSchema = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'Article',
        '@id': `${canonicalUrl}#article`,
        headline: post.title,
        description: post.metaDescription || post.excerpt,
        image: [imgUrl],
        author: {
          '@type': 'Organization',
          '@id': `${baseUrl}/#organization`,
          name: 'NaturesMud',
          url: baseUrl,
        },
        publisher: {
          '@type': 'Organization',
          '@id': `${baseUrl}/#organization`,
          name: 'NaturesMud',
          logo: {
            '@type': 'ImageObject',
            url: `${baseUrl}/icon-512x512.png`,
          },
        },
        datePublished: post.date,
        mainEntityOfPage: {
          '@type': 'WebPage',
          '@id': canonicalUrl,
        },
      },
      {
        '@type': 'BreadcrumbList',
        '@id': `${canonicalUrl}#breadcrumb`,
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Home', item: baseUrl },
          { '@type': 'ListItem', position: 2, name: 'Blog', item: `${baseUrl}/blog` },
          { '@type': 'ListItem', position: 3, name: post.title, item: canonicalUrl },
        ],
      },
      {
        '@type': 'FAQPage',
        '@id': `${canonicalUrl}#faq`,
        mainEntity: activeFaqs.map((f: any) => ({
          '@type': 'Question',
          name: f.question,
          acceptedAnswer: {
            '@type': 'Answer',
            text: f.answer,
          },
        })),
      },
    ],
  };

  return (
    <>
      <BlogPostClient post={post} relatedPosts={related} />

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(blogGraphSchema),
        }}
      />
    </>
  );
}